global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'outbox-relay'
    static_configs:
      - targets: ['outbox-relay:3000']

  - job_name: 'saga-workers'
    static_configs:
      - targets: ['saga-workers:3000']